services:
  qlove_postgres:
    env_file: "/home/ubuntu/qlove/.env"
    image: postgres
    restart: always
    shm_size: 256mb
    ports:
      - 5432:5432
    volumes:
      - $POSTGRES_DATA:/var/lib/postgresql/data

  qlove_api:
    links:
      - qlove_postgres
    env_file: "/home/ubuntu/qlove/.env"
    image: qlove_api:06052025
    ports:
      - 3000:3000
    depends_on:
      - qlove_postgres
      - ca1

# Docker volumne containing the data of the Redis database
# You can safely delete the redis service without losing data
volumes:
  redis:
