default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: qlove_development

test:
  <<: *default
  database: qlove_test

production:
  <<: *default
  database: qlove_production
  username: your_db_username
  password: <%= ENV['DATABASE_PASSWORD'] %>
